In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 730.2 kB/s eta 0:00:17
   -- ------------------------------------- 0.8/12.3 MB 714.3 kB/s eta 0:00:17
   --- ------------------------------------ 1.0/12.3 MB 868.0 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/12.3 MB 871.6 kB/s eta 0:00:13
   ----- ---------------------------------- 1.6/12.3 MB 964.5 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/12.3 MB 964.5 kB/s eta 0:00:12
   ----- ---------------------------------- 1.8/12.3 MB 867.5 kB/s eta 0:00:13
   ----- ---------------------------------- 1.8/12.3 MB 867.5 kB/s eta 0:00:13
   ------ --------------------------------- 2.1/12.3 MB 876.3 kB/s eta 0:00:12
   ------


[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [8]:
arr=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
np.zeros((3, 3))







array([[ 0.3459423 ,  0.48362675],
       [ 0.21984539, -1.61061271],
       [ 0.07951904, -1.12384232]])

In [9]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [12]:

arr[0]



arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

arr[1, :2]
arr = np.array([1, 2, 3, 4, 5])
mask = arr>3
arr[mask]

array([4, 5])

In [13]:




np.hstack((a, b))

array([1, 2, 3, 4])

In [14]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [26]:

arr = np.array([1, 2, 3, 4, 5])
arr[1:4]

array([2, 3, 4])

In [20]:
arr = np.arange(6)

In [21]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [23]:
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [25]:
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')

In [27]:
arr = np.array([1, 2, 3, 4, 5])
arr[::2]

array([1, 3, 5])

In [28]:
arr = np.array([1, 2, 3, 4, 5])
arr[:, 1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [29]:
arr=np.array([1,2,3])
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
arr=np.array([1,2,3])
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr=np.array([1,2,3])
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
arr=np.array([1,2,3])
np.random.randn(3, 2)

array([[-0.57719649, -0.82457224],
       [ 1.15250048, -0.18391536],
       [-0.85098301,  0.43239197]])

In [32]:
arr=np.array([1,2,3])
np.random.rand(3, 2)

array([[0.30742728, 0.25147197],
       [0.13446733, 0.93737403],
       [0.15171698, 0.12624569]])

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)

2


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)

6


In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.dtype)

int64


In [39]:
np.save('array.npy', arr)

In [40]:
loaded_arr = np.load('array.npy')